name: GitHub Actions for Raphtory Deployment
on: [push]
env: 
  PROJECT_ID: '${{ secrets.PROJECT }}'
  GAR_LOCATION: europe-southwest1
  GKE_CLUSTER: '${{ secrets.CLUSTER }}'
  GKE_ZONE: europe-southwest1-a
jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.CREDENTIALS }}'

    - id: 'Deploy'
      name: 'Launch Pulsar and Raphtory'
      run: |
        gcloud config set project "$PROJECT_ID"
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        git clone https://github.com/dpisonero/raphtory_cloud.git
        cd ./raphtory_cloud
        sudo chmod 777 ./Docker/pulsar-mine
        sudo chmod 777 ./Tests/setup_kubetory_Act.py
        ./Docker/pulsar-mine
        cd ./Tests
        python3 ./setup_kubetory_Act.py
