name: GitHub Actions for Raphtory Deployment
on: [push]
env: 
  PROJECT_ID: secrets.GKE_PROJECT
  GAR_LOCATION: europe-southwest1
  GKE_CLUSTER: raphtory-cluster
  GKE_ZONE: europe-southwest1-a
jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      run: |
        ls ${{ github.workspace }}
        git clone https://github.com/dpisonero/raphtory_cloud.git
        cd ./raphtory_cloud
        gcloud auth activate-service-account testupdown@ardent-quarter-347510.iam.gserviceaccount.com --key-file=./Tests/key.json
        gcloud config set project "$PROJECT_ID"
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        ./Docker/pulsar-mine
        echo "Going to sleep"
        sleep(180)
        echo "Forwarding"
        kubectl port-forward service/pulsar-broker --namespace pulsar 6650:6650 &
        kubectl port-forward service/pulsar-broker --namespace pulsar 8080:8080 &
        kubectl port-forward service/pulsar-zookeeper --namespace pulsar 2181:2181 &
      
