name: GitHub Actions for Raphtory Deployment
on: [push]
env: 
  PROJECT_ID: ardent-quarter-347510
  GAR_LOCATION: europe-southwest1
  GKE_CLUSTER: raphtory-cluster
  GKE_ZONE: europe-southwest1-a
jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      run: |
        ls ${{ github.workspace }}
        git clone https://github.com/dpisonero/raphtory_cloud.git
        cd ./raphtory_cloud
        gcloud auth activate-service-account testupdown@ardent-quarter-347510.iam.gserviceaccount.com --key-file=./Tests/key.json
        gcloud config set project ardent-quarter-347510
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        sudo chmod 777 ./Docker/pulsar-mine
        #./Docker/pulsar-mine
