name: GitHub Actions for Raphtory Deployment
on: [push]
env: 
  PROJECT_ID: secrets.GKE_PROJECT
  GAR_LOCATION: europe-southwest1
  GKE_CLUSTER: raphtory-cluster
  GKE_ZONE: europe-southwest1-a
jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      run: |
        ls ${{ github.workspace }}
        gcloud auth activate-service-account testupdown@ardent-quarter-347510.iam.gserviceaccount.com --key-file=/home/runner/work/raphtory_cloud/Tests/key.json
        
      
