name: GitHub Actions for Raphtory Deployment
on: [push]
env: 
  PROJECT_ID: '${{ secrets.PROJECT }}'
  GAR_LOCATION: europe-southwest1
  GKE_CLUSTER: '${{ secrets.CLUSTER }}'
  GKE_ZONE: europe-southwest1-a
jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.CREDENTIALS }}'
        
    - id: 'Docker'
      name: 'Authenticate to Docker'
      uses: docker/login-action@v2
      with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'

    - id: 'Deploy'
      name: 'Launch Pulsar and Raphtory'
      run: |
        git clone https://github.com/dpisonero/raphtory_cloud.git
        cd ./raphtory_cloud
        sudo chmod 777 ./Tests/raphtory-docker-image
        ./Tests/raphtory-docker-image -c build -r docker.io/dpisonero -t mytag -z "./Tests/core-assembly-0.5.jar ./Tests/example-lotr_2.13-0.5.jar"
        docker push dpisonero/raphtory:mytag
        gcloud config set project "$PROJECT_ID"
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        sudo chmod 777 ./Docker/pulsar-mine
        sudo chmod 777 ./Tests/setup_kubetory_Act.py
        ./Docker/pulsar-mine
        cd ./Tests
        python3 ./setup_kubetory_Act.py
