name: GitHub Actions for Raphtory Deployment
on: [push]
env: 
  PROJECT_ID: ardent-quarter-347510
  GAR_LOCATION: europe-southwest1
  GKE_CLUSTER: raphtory-cluster
  GKE_ZONE: europe-southwest1-a
jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credential_json: 
